service: serverless-next

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  home:
    handler: node_modules/next-serverless/lib/server.handler
    events:
      - http: GET /
    environment:
      NODE_ENV: production
  about:
    handler: node_modules/next-serverless/lib/server.handler
    events:
      - http: GET /about
    environment:
      NODE_ENV: production
