service: serverless-next

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1
  environment:
    NODE_ENV: production

custom:
  handler: node_modules/next-serverless/lib/server.handler

functions:
  home:
    handler: ${self:custom.handler}
    events:
      - http: GET /
  about:
    handler: ${self:custom.handler}
    events:
      - http: GET /about
  post:
    handler: ${self:custom.handler}
    events:
      - http: GET /post
